[project]
name = "nur-cn-crawler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bs4>=0.0.2",
    "crawlee[full]==0.4.5",
    "lxml>=5.4.0",
    "plyvel>=1.5.1",
]
